name: springboot-app-pipeline
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy: 
      matrix: 
        java: ['17']
    steps:
      - name: branch checkout
        uses: actions/checkout@v4
      - name: install java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
      - name: mvn build
        run: mvn -f spring-boot-2-rest-service-basic/pom.xml clean package
        continue-on-error: true
      - name: path
        run: |
             pwd
             cd spring-boot-2-rest-service-basic
             ls -al
      # - name: run jar
      #   run: |
      #        JAR_FILE=$(ls spring-boot-2-rest-service-basic/target/*.jar |  head -n 1)
      #        java -jar $JAR_FILE
      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: target/
    
  
